### ISSUE TITLE
Punti da rivedere D2

### ISSUE THREAD

**Issue by FedericoMenegoz** [IS22-TEAM-25/Documents#11]
# D2
### Schermata registrazione 
- [ ] io metterei "richiesta collegamento paypall" invece che dati pagamenti e farei un collegamento con l'interfaccia col sistema di pagamento (che a questo punto si può chiamare gestione paypal?)
- [ ] in "richiesta scrittura dati utente e pagamenti" i dati di pagamento secondo me non vanno al database, perché sono gestiti da paypal
- [x] richiesta login e richiesta registrazione servono per passare da una pagina all'altra?

### Schermata Home
- [x] token di accesso forse collegato anche qui? (anche se cambia solo che ha la tua icona in altro a destra invece che la scritta registrati/effettua login);
- [ ] dalla schermata home manca il flusso di informazione sulle categorie
### Schermata gestione pubblicazione annuncio
- [x] anche qui token d'accesso;
- [x] forse ci vorrebbe un blocco che gestisce google calendar e google maps che poi comunicano questa interfaccia;
### Interfaccia sistema di pagamento
- [x] qua io metterei anche un collegamento con il database che elimini l'articolo se il pagamento è andato a buon fine e al calendario per cambiare (automaticamente) le date di disponibilità in caso di affitto;
### Cose che forse mancano:
- [x] interfaccia per google calendar;
- [x] interfaccia per google maps;
- [x] gestione delle email:
	- [x] conferma email durante la registrazione;
	- [x] email ripristino password;
	- [x] email conseguenti ad una transazione;
- [ ] blocco profilo;
- [ ] possibilità di ricerca dalle varie schermate (dove manca)
- [ ] fare richiesta login/sign up e logout da tutte le pagine
- [ ] manca il semicerchio verso l'esterno con la lista delle chat dall'interfaccia chat 
- [ ] lista annunci in schermata profilo esterno (non mi ricordo bene cosa avevamo deciso, ma mi pare che quando si selezionava un utente si  vedevano anche i suoi annunci)
- [ ] possibilità di passare da una schermata all'altra (dove manca)

**Comment by gabri17** [comment]
Ottimo grazie mille, ho aggiunto le cose segnate. L'unica cosa il blocco profilo che non so come metterlo e secondo me i dati pagamento va bene mandarli anche al db perché poi l'interfaccia con il sistema di pagamento li riceve dagli altri componenti che leggono dal database
